spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:" #Imports configuration data from a config server when available
  cloud:
    config:
      uri: http://localhost:8888  #The url of the Configuration service


server:
  port: 9001

polar:
  greeting: Welcome to the local book catalog